development:
  adapter: postgresql
  host: localhost
  database: mydb
  username: feanaur
  password: password
  pool: 5
 
production:
  adapter: postgresql
  host: localhost
  database: mydb
  pool: 5
  username: feanaur
  password: password