User.create(email: "Myemail@mail.com", name: "Admin", password:"qwerty")
Post.create(user_id: 1, title: "My first post", body: "And this is the post's content.")
Post.create(user_id: 1, title: "Second post", body: "<strong> This must be with bold font</strong>")
Post.create(user_id: 1, title: "Coffee with Ruby", body: "Hard way to concentrate")
Comment.create(user_id: 1, post_id: 1, body: "Comment for the first post")
Comment.create(user_id: 1, post_id: 1, body: "Second comment for the first post")